matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_script:
        - cd anyaelmentem
      script:
        - mvn package
      after_success:
        - cd ../
    - language: node_js
      node_js:
        - "node"
      before_install:
        - cd frontend/anya-elmentem
      install:
        - npm install
      script:
        - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/anya-elmentem/dist
  script:
    - jar -xf target/anyaelmentem-0.0.1-SNAPSHOT.jar
    - java org.springframework.boot.loader.JarLauncher
   
  on:
    branch: master
