matrix:
    include:
        - language: node_js
        node_js:
         - "node"
        cache: npm
        before_install: cd frontend/anya-elmentem
        install: npm install
        script: 
            - npm run build
        - language: java
        jdk: oraclejdk15
        script: 
            - jar -xf anyaelmentem/target/anyaelmentem-0.0.1-SNAPSHOT.jar
            - java org.springframework.boot.loader.JarLauncher
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: frontend/anya-elmentem/dist
 on:
   branch: master
