insert into chores(name) values ('mosogatás')
insert into chores(name) values ('kutyasétáltatás')
insert into chores(name) values ('porszívózás')
insert into chores(name) values ('ablakpucolás')
insert into chores(name) values ('bevásárlás')
insert into chores(name) values ('vasalás')

insert into useres(name,email,password) values('anya','anya@anya.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a')
insert into useres(name,email,password) values('apa','apa@apa.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a')
insert into useres(name,email,password) values('bori','bori@bori.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a')
insert into useres(name,email,password) values('pisti','pisti@pisti.com','$2a$10$c/.qCnqvl7plMmDpIkn.tuT9BaNvEwdifDvK0naj.unS3FNL0d5.a')

insert into group(id) values(1)
insert into group(id) values(2)
insert into group(id) values(3)

insert into todos(id,user,chores,from,to,group_id)values(1,'anya@anya.com','mosogatas',)
insert into todos(id,user,chores,from,to,group_id)values(2,'apa@apa.com','porszívózás',)
insert into todos(id,user,chores,from,to,group_id)values(3,'bori@bori.com','vasalás',)
insert into todos(id,user,chores,from,to,group_id)values(4,'anya@anya.com','mosogatas',)
insert into todos(id,user,chores,from,to,group_id)values(5,'anya@anya.com','mosogatas',)
insert into todos(id,user,chores,from,to,group_id)values(6,'anya@anya.com','mosogatas',)